---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: beck
    app.kubernetes.io/name: beck-todo
  name: beck-todo
  namespace: beck-todo
---
apiVersion: v1
data:
  BECK_STORE: postgres
  RUST_LOG: info
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: beck
    app.kubernetes.io/name: beck-todo
  name: beck-todo-config
  namespace: beck-todo
