[package]
name = "beck-infra"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
beck-core.workspace = true
anyhow.workspace = true
beck-diag.workspace = true
serde.workspace = true
serde_json.workspace = true
k8s-openapi.workspace = true

[dev-dependencies]
insta.workspace = true
serde_norway.workspace = true
beck-core.workspace = true
proptest.workspace = true

[lints]
workspace = true
