//! The workflow `beck init ci` writes — this project's discipline, emitted for somebody else's
//! application.
//!
//! [`docs/28`](../../../../../docs/28-releases-and-deployment.md) §28.3 item 1 specifies it:
//! "`beck check`, `beck test`, `beck check --wire-compat` against the deployed interface, then
//! `beck build` and an image push on merge. Wire-compat is the load-bearing step — the §3.6/§4.3
//! firewall placed where it stops a bad deploy rather than reporting one."
//!
//! # Why the generated file is checked by a harness rather than trusted
//!
//! [`docs/19`](../../../../../docs/19-phase-1-report.md) §19.4 item 10: "an artefact nobody has
//! executed is a design document", and Phase 2 found a workflow of this project's own that had been
//! **invalid YAML from the day it was written**, so every gate in it was silently absent
//! (`workflows.rs`). A generator that emits such a file emits it into every repository that runs
//! `beck init ci`. So `init_ci.rs` runs the same reserved-indicator check over the *generated* text,
//! parses it with somebody else's YAML parser, and — the part that only a generator can get wrong —
//! asserts that every `beck <subcommand>` it invokes is a subcommand the binary actually has.
//!
//! # What it will not pretend
//!
//! There is no published `beck` release ([`docs/28`](../../../../../docs/28-releases-and-deployment.md)
//! §28.1), so there is no action to `uses:` for installing one. The workflow therefore builds the
//! toolchain from a checkout, and says so in a comment naming what will replace it. Emitting
//! `uses: beck-lang/setup-beck@v1` would be a workflow that fails on its first run in every
//! repository that generated one.

use crate::InfraGraph;

/// Where the workflow goes, relative to the repository root.
pub const WORKFLOW_PATH: &str = ".github/workflows/beck.yml";

/// The interface a previous release published, which `--wire-compat` compares against.
///
/// A path rather than a lookup: the released `.becki` is a file somebody reviews and commits
/// ([`docs/03`](../../../../../docs/03-type-and-effect-system.md) §3.6), so the workflow can name
/// it, and the step is skipped with a message when it is not there rather than failing a repository
/// that has never released.
pub const RELEASED_IFACE: &str = "released/app.becki";

/// The workflow, for an application whose source is `app`.
///
/// `app` is the path to the program inside the repository — the argument every step passes, and the
/// one thing about a user's repository this generator knows.
pub fn workflow(graph: &InfraGraph, app: &str) -> String {
    let name = &graph.app;
    format!(
        "# Generated by `beck init ci`. Reviewed and committed like any other file: this is the\n\
         # gate on {name}, so a change to it is a change to what may be deployed.\n\
         #\n\
         # The discipline is docs/28 §28.3: check, test, wire-compat, build — then, on the default\n\
         # branch, an image and a signature. `--wire-compat` is the load-bearing step; it is the\n\
         # §4.3 firewall placed where it stops a bad deploy rather than reporting one.\n\
         name: {name}\n\n\
         on:\n  \
         push:\n    branches: [main]\n  \
         pull_request:\n\n\
         # Read, and nothing else. Nothing in this file writes to the repository, and nothing\n\
         # pushes to a registry — `beck image` writes a layout and does not upload it, so a\n\
         # `packages: write` here would be a permission granted for something that does not\n\
         # happen. Add it with the push step, not before.\n\
         permissions:\n  contents: read\n\n\
         env:\n  BECK_APP: {app}\n\n\
         jobs:\n  \
         check:\n    \
         runs-on: ubuntu-latest\n    \
         steps:\n      \
         - uses: actions/checkout@v5\n\n      \
         # There is no published Beck release yet (docs/28 §28.1), so the toolchain is built\n      \
         # from source. Replace this step with the released binary when there is one — nothing\n      \
         # else in this file changes when you do.\n      \
         - name: Build the toolchain\n        \
         run: |\n          \
         cargo install --locked --git https://github.com/georgestephenson/beck beck-cli\n\n      \
         - name: Placement is the one the lock records\n        \
         run: beck check \"$BECK_APP\" --locked\n\n      \
         - name: The program's own tests\n        \
         run: beck test \"$BECK_APP\"\n\n      \
         # The released interface, if this application has released one. A repository that\n      \
         # has not yet is not failed by its absence; a repository that has cannot merge a\n      \
         # breaking change without saying `--breaking` here, which is a reviewable diff.\n      \
         - name: The wire contract still holds\n        \
         run: |\n          \
         if [ -f \"{iface}\" ]; then\n            \
         beck check \"$BECK_APP\" --wire-compat \"{iface}\"\n          \
         else\n            \
         echo \"no {iface} — nothing released to be compatible with\"\n          \
         fi\n\n      \
         - name: The deployable system, and its bill of materials\n        \
         run: beck build \"$BECK_APP\" --out target/beck\n\n      \
         - name: Manifests apply to a real API server\n        \
         run: beck up \"$BECK_APP\" --dry-run\n\n      \
         - uses: actions/upload-artifact@v4\n        \
         with:\n          \
         name: manifests\n          \
         path: target/beck\n\n  \
         # The image, and only from the default branch: a signature made on a pull request\n  \
         # is a signature over code nobody has approved.\n  \
         image:\n    \
         needs: check\n    \
         if: github.ref == 'refs/heads/main'\n    \
         runs-on: ubuntu-latest\n    \
         steps:\n      \
         - uses: actions/checkout@v5\n\n      \
         - name: Build the toolchain\n        \
         run: |\n          \
         cargo install --locked --git https://github.com/georgestephenson/beck beck-cli\n\n      \
         # One process: no apko, no melange, no daemon, no registry client. It resolves\n      \
         # the packages, unpacks them and writes an OCI layout (docs/06 §6.2).\n      \
         - name: The image\n        \
         run: beck image \"$BECK_APP\" --out target/image --tag \"$GITHUB_SHA\"\n\n      \
         # Reproducibility as a gate, not as a claim: the same inputs twice, and the\n      \
         # digests compared (docs/28 §28.2 item 3).\n      \
         - name: The same image twice\n        \
         run: |\n          \
         beck image \"$BECK_APP\" --out target/image-again --tag \"$GITHUB_SHA\"\n          \
         diff target/image/index.json target/image-again/index.json\n\n      \
         # The key is a repository secret holding the PEM `beck key generate` wrote. Its\n      \
         # public half belongs in the repository, so a consumer can run\n      \
         # `cosign verify --key cosign.pub`.\n      \
         - name: Sign it\n        \
         env:\n          \
         BECK_SIGNING_KEY: ${{{{ secrets.BECK_SIGNING_KEY }}}}\n        \
         run: beck sign target/image\n\n      \
         - uses: actions/upload-artifact@v4\n        \
         with:\n          \
         name: image\n          \
         path: target/image\n",
        iface = RELEASED_IFACE,
    )
}

/// Every `beck <subcommand>` the generated workflow runs, in order of appearance.
///
/// Exported because the gate needs it: a generator that emits a command the binary does not have
/// writes a workflow that fails on its first run, and the only way to notice is to compare against
/// the command tree. Reading the emitted text rather than a list kept beside it is
/// [`docs/92`](../../../../../docs/92-sbom-report.md) §92.2's rule — a proxy for a control is
/// defeated by naming.
pub fn invocations(workflow: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in workflow.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        let mut rest = line;
        while let Some(at) = rest.find("beck ") {
            // `cargo install … beck-cli` and the `$BECK_APP` variable are not invocations; a
            // subcommand is the word after `beck ` when `beck` is the start of a word.
            let before = rest[..at].chars().next_back();
            rest = &rest[at + "beck ".len()..];
            if before.is_some_and(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') {
                continue;
            }
            let word = rest
                .split_whitespace()
                .next()
                .unwrap_or_default()
                .trim_matches('"');
            if !word.is_empty() && word.chars().all(|c| c.is_ascii_lowercase()) {
                out.push(word.to_string());
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn graph() -> InfraGraph {
        crate::derive("todo", &[], true)
    }

    #[test]
    fn the_workflow_runs_the_steps_28_3_specifies() {
        let text = workflow(&graph(), "app.beck");
        for required in ["--locked", "beck test", "--wire-compat", "beck build"] {
            assert!(
                text.contains(required),
                "the workflow no longer runs {required}"
            );
        }
    }

    #[test]
    fn every_command_it_runs_is_a_word_the_cli_could_have() {
        let text = workflow(&graph(), "app.beck");
        let commands = invocations(&text);
        assert!(
            commands.contains(&"check".to_string()) && commands.contains(&"image".to_string()),
            "found {commands:?}"
        );
        // The binary's own name inside `cargo install … beck-cli` is not an invocation.
        assert!(
            !commands.iter().any(|c| c.contains("cli")),
            "found {commands:?}"
        );
    }
}
